#!/usr/bin/env bash

function usage() {
    echo "Usage: $0 [command]"
}

function init() {
    ./zsh/zsh.sh init
    ./git/git.sh
}

function update() {
    ./zsh/zsh.sh update
    ./git/git.sh
}

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

COMMAND=$1

case "$COMMAND" in
	init)
	   init
	   ;;
	update)
	   update
	   ;;
	*)
	   usage
           ;;
esac